services:
  - type: web
    name: ai-code-reviewer-backend
    env: python
    plan: free
    region: oregon
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GEMINI_API_KEY
        value: key
    autoDeploy: true
    pythonVersion: 3.10.12
